version: 2

sources:
  - name: gz_raw_data
    database: project-a9786291-b642-4e23-a55
    schema: gz_raw_data
    loader: bigquery
    description: raw data of product, sales and ship

    tables:
      - name: raw_gz_product
        description: product purchase prices
        columns:
          - name: products_id
            description: id of the product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchased price of the product

      - name: raw_gz_sales
        description: Sales with orders products quantities and revenue
        tests:
          - unique:
              column_name: (orders_id || '_' || pdt_id)
        columns:
          - name: date_date
            description: date of order
          - name: orders_id
            description: id of the order
            tests:
              - not_null
          - name: pdt_id
            description: id of the product in the order
            tests:
              - not_null
          - name: revenue
            description: revenue of the order
          - name: quantity
            description: qty of product in the order

      - name: raw_gz_ship
        description: shipping fees and logistics costs by order
        columns:
          - name: orders_id
            description: id of the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee of the order
          - name: log_cost
            description: logistic cost of the order
          - name: ship_cost
            description: shipping cost of the order

    


